apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  secret-file: SU5JVElBTF9LRVk=
---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"