apiVersion: v1
kind: Secret
metadata:
  name: dotfile-secret
data:
  secret-file: SU5JVElBTF9LRVk=




---
apiVersion: v1
kind: Pod
metadata:
  name: secret-dotfiles-pod
spec:
  volumes:
    - name: secret-volume
      secret:
        secretName: dotfile-secret
  containers:
    - name: dotfile-test-container
      image: busybox
      command: ["sleep", "3600"]
      volumeMounts:
        - name: secret-volume
          readOnly: true
          mountPath: "/etc/secret-volume"

---


apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: default



---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-editor
  namespace: default
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "update"]


---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-editor-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: cronjob-sa
  namespace: default
roleRef:
  kind: Role
  name: secret-editor
  apiGroup: rbac.authorization.k8s.io

---

